# Dockerfile for Django (backend)
# Build the Django app
FROM python:3.8

WORKDIR /app

COPY backend/requirements.txt ./
RUN pip install -r requirements.txt

COPY backend/ ./

RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

# Expose the port for Django
EXPOSE 5000

# Start the Django development server
CMD ["python3", "manage.py", "runserver", "0.0.0.0:5000"]