services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1  # Set environment variables as needed

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
