# Generated by Django 4.2.16 on 2024-10-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_token_user_token_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes_to_enroll',
            field=models.TextField(default='[]'),
        ),
    ]
