# Generated by Django 4.2.16 on 2024-10-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_token_user_id_token_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
