# Generated by Django 4.2.16 on 2024-10-06 21:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_classes_to_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classes_to_enroll',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
