# Generated by Django 4.2.16 on 2024-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_classes_to_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_to_enroll_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('hour', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='classes_to_enroll',
        ),
    ]
